import 'dotenv/config';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '../src/generated/prisma/client.js';
import {
  ContentTier,
  PlayerPosition,
  PreferredFoot,
} from '../src/generated/prisma/enums.js';

const connectionString = process.env['DATABASE_URL'];

if (!connectionString) {
  throw new Error('DATABASE_URL is required.');
}

const DATA_VERSION = '1.0.0';
const SOURCE_PROVIDER = 'footbid-seed';

const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

type ClubKey = 'comets' | 'tides';

interface SeedPlayer {
  sourcePlayerId: string;
  clubKey: ClubKey;
  fullName: string;
  shortName: string;
  nationalityCode: string;
  primaryPosition: PlayerPosition;
  secondaryPositions: PlayerPosition[];
  preferredFoot: PreferredFoot;
  overall: number;
  pace: number;
  shooting: number;
  passing: number;
  dribbling: number;
  defending: number;
  physical: number;
  goalkeeping: number;
  marketValue: number;
}

const players: SeedPlayer[] = [
  {
    sourcePlayerId: 'comets-01',
    clubKey: 'comets',
    fullName: 'Amin Rahman',
    shortName: 'A. Rahman',
    nationalityCode: 'BD',
    primaryPosition: PlayerPosition.GK,
    secondaryPositions: [],
    preferredFoot: PreferredFoot.RIGHT,
    overall: 74,
    pace: 50,
    shooting: 14,
    passing: 60,
    dribbling: 48,
    defending: 18,
    physical: 71,
    goalkeeping: 76,
    marketValue: 6_000_000,
  },
  {
    sourcePlayerId: 'comets-02',
    clubKey: 'comets',
    fullName: 'Rafi Noor',
    shortName: 'R. Noor',
    nationalityCode: 'BD',
    primaryPosition: PlayerPosition.LB,
    secondaryPositions: [PlayerPosition.LWB],
    preferredFoot: PreferredFoot.LEFT,
    overall: 72,
    pace: 78,
    shooting: 50,
    passing: 68,
    dribbling: 72,
    defending: 70,
    physical: 69,
    goalkeeping: 8,
    marketValue: 5_000_000,
  },
  {
    sourcePlayerId: 'comets-03',
    clubKey: 'comets',
    fullName: 'Samiq Hasan',
    shortName: 'S. Hasan',
    nationalityCode: 'BD',
    primaryPosition: PlayerPosition.CB,
    secondaryPositions: [],
    preferredFoot: PreferredFoot.LEFT,
    overall: 74,
    pace: 65,
    shooting: 38,
    passing: 61,
    dribbling: 57,
    defending: 76,
    physical: 78,
    goalkeeping: 9,
    marketValue: 7_000_000,
  },
  {
    sourcePlayerId: 'comets-04',
    clubKey: 'comets',
    fullName: 'Kabir Ahmed',
    shortName: 'K. Ahmed',
    nationalityCode: 'BD',
    primaryPosition: PlayerPosition.CB,
    secondaryPositions: [],
    preferredFoot: PreferredFoot.RIGHT,
    overall: 75,
    pace: 61,
    shooting: 35,
    passing: 63,
    dribbling: 55,
    defending: 78,
    physical: 80,
    goalkeeping: 8,
    marketValue: 8_000_000,
  },
  {
    sourcePlayerId: 'comets-05',
    clubKey: 'comets',
    fullName: 'Tanvir Alam',
    shortName: 'T. Alam',
    nationalityCode: 'BD',
    primaryPosition: PlayerPosition.RB,
    secondaryPositions: [PlayerPosition.RWB],
    preferredFoot: PreferredFoot.RIGHT,
    overall: 73,
    pace: 80,
    shooting: 48,
    passing: 67,
    dribbling: 70,
    defending: 71,
    physical: 70,
    goalkeeping: 7,
    marketValue: 6_000_000,
  },
  {
    sourcePlayerId: 'comets-06',
    clubKey: 'comets',
    fullName: 'Farhan Chowdhury',
    shortName: 'F. Chowdhury',
    nationalityCode: 'BD',
    primaryPosition: PlayerPosition.CM,
    secondaryPositions: [PlayerPosition.CDM],
    preferredFoot: PreferredFoot.RIGHT,
    overall: 76,
    pace: 70,
    shooting: 70,
    passing: 78,
    dribbling: 76,
    defending: 68,
    physical: 72,
    goalkeeping: 8,
    marketValue: 10_000_000,
  },
  {
    sourcePlayerId: 'comets-07',
    clubKey: 'comets',
    fullName: 'Nabil Karim',
    shortName: 'N. Karim',
    nationalityCode: 'BD',
    primaryPosition: PlayerPosition.CM,
    secondaryPositions: [PlayerPosition.CAM],
    preferredFoot: PreferredFoot.LEFT,
    overall: 77,
    pace: 75,
    shooting: 74,
    passing: 79,
    dribbling: 80,
    defending: 48,
    physical: 65,
    goalkeeping: 6,
    marketValue: 12_000_000,
  },
  {
    sourcePlayerId: 'comets-08',
    clubKey: 'comets',
    fullName: 'Zayan Islam',
    shortName: 'Z. Islam',
    nationalityCode: 'BD',
    primaryPosition: PlayerPosition.LM,
    secondaryPositions: [PlayerPosition.LW],
    preferredFoot: PreferredFoot.LEFT,
    overall: 74,
    pace: 82,
    shooting: 68,
    passing: 72,
    dribbling: 75,
    defending: 45,
    physical: 62,
    goalkeeping: 7,
    marketValue: 8_000_000,
  },
  {
    sourcePlayerId: 'comets-09',
    clubKey: 'comets',
    fullName: 'Arif Hossain',
    shortName: 'A. Hossain',
    nationalityCode: 'BD',
    primaryPosition: PlayerPosition.RM,
    secondaryPositions: [PlayerPosition.RW],
    preferredFoot: PreferredFoot.RIGHT,
    overall: 75,
    pace: 84,
    shooting: 70,
    passing: 73,
    dribbling: 77,
    defending: 42,
    physical: 64,
    goalkeeping: 6,
    marketValue: 9_000_000,
  },
  {
    sourcePlayerId: 'comets-10',
    clubKey: 'comets',
    fullName: 'Imran Sayeed',
    shortName: 'I. Sayeed',
    nationalityCode: 'BD',
    primaryPosition: PlayerPosition.ST,
    secondaryPositions: [PlayerPosition.CF],
    preferredFoot: PreferredFoot.RIGHT,
    overall: 78,
    pace: 82,
    shooting: 80,
    passing: 68,
    dribbling: 75,
    defending: 35,
    physical: 76,
    goalkeeping: 7,
    marketValue: 15_000_000,
  },
  {
    sourcePlayerId: 'comets-11',
    clubKey: 'comets',
    fullName: 'Tahmid Bashar',
    shortName: 'T. Bashar',
    nationalityCode: 'BD',
    primaryPosition: PlayerPosition.ST,
    secondaryPositions: [PlayerPosition.CF],
    preferredFoot: PreferredFoot.LEFT,
    overall: 76,
    pace: 78,
    shooting: 79,
    passing: 65,
    dribbling: 73,
    defending: 32,
    physical: 78,
    goalkeeping: 5,
    marketValue: 11_000_000,
  },
  {
    sourcePlayerId: 'tides-01',
    clubKey: 'tides',
    fullName: 'Rehan Malik',
    shortName: 'R. Malik',
    nationalityCode: 'BD',
    primaryPosition: PlayerPosition.GK,
    secondaryPositions: [],
    preferredFoot: PreferredFoot.RIGHT,
    overall: 75,
    pace: 48,
    shooting: 13,
    passing: 62,
    dribbling: 49,
    defending: 20,
    physical: 73,
    goalkeeping: 77,
    marketValue: 7_000_000,
  },
  {
    sourcePlayerId: 'tides-02',
    clubKey: 'tides',
    fullName: 'Ayan Das',
    shortName: 'A. Das',
    nationalityCode: 'BD',
    primaryPosition: PlayerPosition.LB,
    secondaryPositions: [PlayerPosition.LWB],
    preferredFoot: PreferredFoot.LEFT,
    overall: 73,
    pace: 81,
    shooting: 49,
    passing: 69,
    dribbling: 73,
    defending: 71,
    physical: 68,
    goalkeeping: 7,
    marketValue: 6_000_000,
  },
  {
    sourcePlayerId: 'tides-03',
    clubKey: 'tides',
    fullName: 'Sakib Roy',
    shortName: 'S. Roy',
    nationalityCode: 'BD',
    primaryPosition: PlayerPosition.CB,
    secondaryPositions: [],
    preferredFoot: PreferredFoot.LEFT,
    overall: 75,
    pace: 67,
    shooting: 36,
    passing: 64,
    dribbling: 58,
    defending: 78,
    physical: 77,
    goalkeeping: 9,
    marketValue: 8_000_000,
  },
  {
    sourcePlayerId: 'tides-04',
    clubKey: 'tides',
    fullName: 'Fahim Bari',
    shortName: 'F. Bari',
    nationalityCode: 'BD',
    primaryPosition: PlayerPosition.CB,
    secondaryPositions: [],
    preferredFoot: PreferredFoot.RIGHT,
    overall: 76,
    pace: 63,
    shooting: 34,
    passing: 62,
    dribbling: 56,
    defending: 79,
    physical: 82,
    goalkeeping: 8,
    marketValue: 9_000_000,
  },
  {
    sourcePlayerId: 'tides-05',
    clubKey: 'tides',
    fullName: 'Omar Haque',
    shortName: 'O. Haque',
    nationalityCode: 'BD',
    primaryPosition: PlayerPosition.RB,
    secondaryPositions: [PlayerPosition.RWB],
    preferredFoot: PreferredFoot.RIGHT,
    overall: 74,
    pace: 82,
    shooting: 51,
    passing: 68,
    dribbling: 72,
    defending: 72,
    physical: 71,
    goalkeeping: 6,
    marketValue: 7_000_000,
  },
  {
    sourcePlayerId: 'tides-06',
    clubKey: 'tides',
    fullName: 'Adnan Sarker',
    shortName: 'A. Sarker',
    nationalityCode: 'BD',
    primaryPosition: PlayerPosition.CDM,
    secondaryPositions: [PlayerPosition.CM],
    preferredFoot: PreferredFoot.RIGHT,
    overall: 76,
    pace: 68,
    shooting: 62,
    passing: 75,
    dribbling: 72,
    defending: 76,
    physical: 79,
    goalkeeping: 7,
    marketValue: 10_000_000,
  },
  {
    sourcePlayerId: 'tides-07',
    clubKey: 'tides',
    fullName: 'Rayhan Kabir',
    shortName: 'R. Kabir',
    nationalityCode: 'BD',
    primaryPosition: PlayerPosition.CM,
    secondaryPositions: [PlayerPosition.CAM],
    preferredFoot: PreferredFoot.BOTH,
    overall: 78,
    pace: 73,
    shooting: 75,
    passing: 80,
    dribbling: 79,
    defending: 62,
    physical: 70,
    goalkeeping: 8,
    marketValue: 14_000_000,
  },
  {
    sourcePlayerId: 'tides-08',
    clubKey: 'tides',
    fullName: 'Miraj Uddin',
    shortName: 'M. Uddin',
    nationalityCode: 'BD',
    primaryPosition: PlayerPosition.LW,
    secondaryPositions: [PlayerPosition.LM],
    preferredFoot: PreferredFoot.LEFT,
    overall: 76,
    pace: 86,
    shooting: 72,
    passing: 73,
    dribbling: 80,
    defending: 40,
    physical: 63,
    goalkeeping: 5,
    marketValue: 11_000_000,
  },
  {
    sourcePlayerId: 'tides-09',
    clubKey: 'tides',
    fullName: 'Shafin Khan',
    shortName: 'S. Khan',
    nationalityCode: 'BD',
    primaryPosition: PlayerPosition.RW,
    secondaryPositions: [PlayerPosition.RM],
    preferredFoot: PreferredFoot.RIGHT,
    overall: 77,
    pace: 87,
    shooting: 74,
    passing: 74,
    dribbling: 81,
    defending: 39,
    physical: 65,
    goalkeeping: 6,
    marketValue: 13_000_000,
  },
  {
    sourcePlayerId: 'tides-10',
    clubKey: 'tides',
    fullName: 'Zubair Hasan',
    shortName: 'Z. Hasan',
    nationalityCode: 'BD',
    primaryPosition: PlayerPosition.CF,
    secondaryPositions: [PlayerPosition.ST, PlayerPosition.CAM],
    preferredFoot: PreferredFoot.LEFT,
    overall: 77,
    pace: 79,
    shooting: 78,
    passing: 72,
    dribbling: 78,
    defending: 34,
    physical: 72,
    goalkeeping: 7,
    marketValue: 13_000_000,
  },
  {
    sourcePlayerId: 'tides-11',
    clubKey: 'tides',
    fullName: 'Mahir Ahmed',
    shortName: 'M. Ahmed',
    nationalityCode: 'BD',
    primaryPosition: PlayerPosition.ST,
    secondaryPositions: [PlayerPosition.CF],
    preferredFoot: PreferredFoot.RIGHT,
    overall: 79,
    pace: 83,
    shooting: 82,
    passing: 69,
    dribbling: 77,
    defending: 31,
    physical: 80,
    goalkeeping: 5,
    marketValue: 17_000_000,
  },
];

async function main(): Promise<void> {
  const league = await prisma.league.upsert({
    where: {
      slug: 'footbid-premier-league',
    },
    update: {
      name: 'KickoffBid Premier League',
      countryCode: 'BD',
      dataVersion: DATA_VERSION,
      sourceProvider: SOURCE_PROVIDER,
      sourceLeagueId: 'league-001',
    },
    create: {
      name: 'KickoffBid Premier League',
      slug: 'footbid-premier-league',
      countryCode: 'BD',
      dataVersion: DATA_VERSION,
      sourceProvider: SOURCE_PROVIDER,
      sourceLeagueId: 'league-001',
    },
  });

  const [comets, tides] = await Promise.all([
    prisma.club.upsert({
      where: {
        sourceProvider_sourceClubId: {
          sourceProvider: SOURCE_PROVIDER,
          sourceClubId: 'club-comets',
        },
      },
      update: {
        name: 'Dhaka Comets',
        shortName: 'COMETS',
        countryCode: 'BD',
        dataVersion: DATA_VERSION,
        league: { connect: { id: league.id } },
      },
      create: {
        name: 'Dhaka Comets',
        shortName: 'COMETS',
        countryCode: 'BD',
        dataVersion: DATA_VERSION,
        sourceProvider: SOURCE_PROVIDER,
        sourceClubId: 'club-comets',
        league: { connect: { id: league.id } },
      },
    }),
    prisma.club.upsert({
      where: {
        sourceProvider_sourceClubId: {
          sourceProvider: SOURCE_PROVIDER,
          sourceClubId: 'club-tides',
        },
      },
      update: {
        name: 'Chattogram Tides',
        shortName: 'TIDES',
        countryCode: 'BD',
        dataVersion: DATA_VERSION,
        league: { connect: { id: league.id } },
      },
      create: {
        name: 'Chattogram Tides',
        shortName: 'TIDES',
        countryCode: 'BD',
        dataVersion: DATA_VERSION,
        sourceProvider: SOURCE_PROVIDER,
        sourceClubId: 'club-tides',
        league: { connect: { id: league.id } },
      },
    }),
  ]);

  const clubs = { comets, tides };

  for (const player of players) {
    const { sourcePlayerId, clubKey, ...playerData } = player;
    const club = clubs[clubKey];

    await prisma.player.upsert({
      where: {
        sourceProvider_sourcePlayerId: {
          sourceProvider: SOURCE_PROVIDER,
          sourcePlayerId,
        },
      },
      update: {
        ...playerData,
        dataVersion: DATA_VERSION,
        isActive: true,
        league: { connect: { id: league.id } },
        club: { connect: { id: club.id } },
      },
      create: {
        ...playerData,
        sourceProvider: SOURCE_PROVIDER,
        sourcePlayerId,
        dataVersion: DATA_VERSION,
        isActive: true,
        league: { connect: { id: league.id } },
        club: { connect: { id: club.id } },
      },
    });
  }

  await prisma.manager.upsert({
    where: {
      sourceProvider_sourceManagerId: {
        sourceProvider: SOURCE_PROVIDER,
        sourceManagerId: 'neutral-coach',
      },
    },
    update: {
      fullName: 'KickoffBid Neutral Coach',
      nationalityCode: 'BD',
      tacticalStyle: 'Balanced',
      overall: 65,
      attacking: 65,
      defending: 65,
      adaptability: 65,
      manManagement: 65,
      tier: ContentTier.FREE,
      isNeutral: true,
      dataVersion: DATA_VERSION,
      league: { disconnect: true },
      club: { disconnect: true },
    },
    create: {
      fullName: 'KickoffBid Neutral Coach',
      nationalityCode: 'BD',
      tacticalStyle: 'Balanced',
      overall: 65,
      attacking: 65,
      defending: 65,
      adaptability: 65,
      manManagement: 65,
      tier: ContentTier.FREE,
      isNeutral: true,
      sourceProvider: SOURCE_PROVIDER,
      sourceManagerId: 'neutral-coach',
      dataVersion: DATA_VERSION,
    },
  });

  await prisma.manager.upsert({
    where: {
      sourceProvider_sourceManagerId: {
        sourceProvider: SOURCE_PROVIDER,
        sourceManagerId: 'premium-manager',
      },
    },
    update: {
      fullName: 'Nayeem Rahman',
      nationalityCode: 'BD',
      tacticalStyle: 'High Press',
      overall: 82,
      attacking: 84,
      defending: 78,
      adaptability: 81,
      manManagement: 83,
      tier: ContentTier.PREMIUM,
      isNeutral: false,
      dataVersion: DATA_VERSION,
      league: { connect: { id: league.id } },
      club: { connect: { id: comets.id } },
    },
    create: {
      fullName: 'Nayeem Rahman',
      nationalityCode: 'BD',
      tacticalStyle: 'High Press',
      overall: 82,
      attacking: 84,
      defending: 78,
      adaptability: 81,
      manManagement: 83,
      tier: ContentTier.PREMIUM,
      isNeutral: false,
      sourceProvider: SOURCE_PROVIDER,
      sourceManagerId: 'premium-manager',
      dataVersion: DATA_VERSION,
      league: { connect: { id: league.id } },
      club: { connect: { id: comets.id } },
    },
  });

  await prisma.formation.upsert({
    where: { code: '4-4-2' },
    update: {
      name: 'Classic 4-4-2',
      description: 'Free balanced formation available to both participants.',
      tier: ContentTier.FREE,
      isNeutral: true,
      dataVersion: DATA_VERSION,
      shape: {
        version: 1,
        slots: [
          { slot: 1, position: 'GK', x: 50, y: 90 },
          { slot: 2, position: 'LB', x: 15, y: 72 },
          { slot: 3, position: 'CB', x: 38, y: 75 },
          { slot: 4, position: 'CB', x: 62, y: 75 },
          { slot: 5, position: 'RB', x: 85, y: 72 },
          { slot: 6, position: 'LM', x: 15, y: 48 },
          { slot: 7, position: 'CM', x: 40, y: 52 },
          { slot: 8, position: 'CM', x: 60, y: 52 },
          { slot: 9, position: 'RM', x: 85, y: 48 },
          { slot: 10, position: 'ST', x: 38, y: 22 },
          { slot: 11, position: 'ST', x: 62, y: 22 },
        ],
      },
    },
    create: {
      code: '4-4-2',
      name: 'Classic 4-4-2',
      description: 'Free balanced formation available to both participants.',
      tier: ContentTier.FREE,
      isNeutral: true,
      dataVersion: DATA_VERSION,
      shape: {
        version: 1,
        slots: [
          { slot: 1, position: 'GK', x: 50, y: 90 },
          { slot: 2, position: 'LB', x: 15, y: 72 },
          { slot: 3, position: 'CB', x: 38, y: 75 },
          { slot: 4, position: 'CB', x: 62, y: 75 },
          { slot: 5, position: 'RB', x: 85, y: 72 },
          { slot: 6, position: 'LM', x: 15, y: 48 },
          { slot: 7, position: 'CM', x: 40, y: 52 },
          { slot: 8, position: 'CM', x: 60, y: 52 },
          { slot: 9, position: 'RM', x: 85, y: 48 },
          { slot: 10, position: 'ST', x: 38, y: 22 },
          { slot: 11, position: 'ST', x: 62, y: 22 },
        ],
      },
    },
  });

  await prisma.formation.upsert({
    where: { code: '4-3-3-attack' },
    update: {
      name: 'Attacking 4-3-3',
      description:
        'Premium formation focused on width and aggressive pressing.',
      tier: ContentTier.PREMIUM,
      isNeutral: false,
      dataVersion: DATA_VERSION,
      shape: {
        version: 1,
        slots: [
          { slot: 1, position: 'GK', x: 50, y: 90 },
          { slot: 2, position: 'LB', x: 15, y: 72 },
          { slot: 3, position: 'CB', x: 38, y: 75 },
          { slot: 4, position: 'CB', x: 62, y: 75 },
          { slot: 5, position: 'RB', x: 85, y: 72 },
          { slot: 6, position: 'CM', x: 35, y: 53 },
          { slot: 7, position: 'CM', x: 65, y: 53 },
          { slot: 8, position: 'CAM', x: 50, y: 42 },
          { slot: 9, position: 'LW', x: 20, y: 22 },
          { slot: 10, position: 'ST', x: 50, y: 18 },
          { slot: 11, position: 'RW', x: 80, y: 22 },
        ],
      },
    },
    create: {
      code: '4-3-3-attack',
      name: 'Attacking 4-3-3',
      description:
        'Premium formation focused on width and aggressive pressing.',
      tier: ContentTier.PREMIUM,
      isNeutral: false,
      dataVersion: DATA_VERSION,
      shape: {
        version: 1,
        slots: [
          { slot: 1, position: 'GK', x: 50, y: 90 },
          { slot: 2, position: 'LB', x: 15, y: 72 },
          { slot: 3, position: 'CB', x: 38, y: 75 },
          { slot: 4, position: 'CB', x: 62, y: 75 },
          { slot: 5, position: 'RB', x: 85, y: 72 },
          { slot: 6, position: 'CM', x: 35, y: 53 },
          { slot: 7, position: 'CM', x: 65, y: 53 },
          { slot: 8, position: 'CAM', x: 50, y: 42 },
          { slot: 9, position: 'LW', x: 20, y: 22 },
          { slot: 10, position: 'ST', x: 50, y: 18 },
          { slot: 11, position: 'RW', x: 80, y: 22 },
        ],
      },
    },
  });

  const [leagueCount, clubCount, playerCount, managerCount, formationCount] =
    await Promise.all([
      prisma.league.count({
        where: { sourceProvider: SOURCE_PROVIDER },
      }),
      prisma.club.count({
        where: { sourceProvider: SOURCE_PROVIDER },
      }),
      prisma.player.count({
        where: { sourceProvider: SOURCE_PROVIDER },
      }),
      prisma.manager.count({
        where: { sourceProvider: SOURCE_PROVIDER },
      }),
      prisma.formation.count({
        where: {
          code: { in: ['4-4-2', '4-3-3-attack'] },
        },
      }),
    ]);

  console.log('KickoffBid fictional seed completed.');
  console.log({
    leagues: leagueCount,
    clubs: clubCount,
    players: playerCount,
    managers: managerCount,
    formations: formationCount,
  });
}

main()
  .catch((error: unknown) => {
    console.error('KickoffBid seed failed:', error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
