export const AUCTION_MAX_PRICE = 150_000_000;
export const AUCTION_MIN_OPENING_PRICE = 100_000;

export const AUCTION_MIN_INCREMENT = 100_000;
export const AUCTION_MAX_INCREMENT = 10_000_000;

export const AUCTION_MIN_DURATION_SECONDS = 15;
export const AUCTION_MAX_DURATION_SECONDS = 300;
export const AUCTION_DEFAULT_DURATION_SECONDS = 30;
export const AUCTION_LAST_CALL_SECONDS = 10;

export const AUCTION_SERIALIZABLE_RETRIES = 4;

export const AUCTION_SOCKET_NAMESPACE = '/auctions';
export const AUCTION_ROOM_PREFIX = 'auction:';

export const AUCTION_SOCKET_BID_LIMIT = 8;
export const AUCTION_SOCKET_BID_WINDOW_MS = 2_000;
